version: "2"
services:
  backoffice-api:
    image: localhost/backoffice-core:1.0.0
    build: .
    container_name: backoffice-core
    restart: unless-stopped
    volumes:
      - ./.env:/app/env:ro      
      - ./src:/app/src           
      - ./prisma/schema.prisma:/app/prisma/schema.prisma 
    ports:
      - "5001:5001"
networks:
  db:
    external: true