version: "2"
services:
  backoffice-api:
    image: localhost/sirine-backend:1.0.0
    build: .
    container_name: sirine-backend
    restart: unless-stopped
    volumes:
      - .env:/app/.env
      - ./src:/app/src
      - ./prisma/schema.prisma:/app/prisma/schema.prisma
    ports:
      - "5004:5004"
networks:
  db:
    external: true
